861 improve frontend tests
dedica-team/nivio pull request #862
Opened 2022-01-24 11:12 UTC by robrobert99

2022-01-24 11:33 UTC, bonndan commented on .github/workflows/cypress_tests.yml
> +      - develop
add `- 245_improve_frontend_tests` here to run against this branch

2022-01-24 11:34 UTC, bonndan commented on .github/workflows/cypress_tests.yml
> +          wait-on: http://localhost:3000
how will that work?

2022-01-31 07:28 UTC, bonndan requested changes
Please add some lines in development.md how to run the cypress tests and add a link to the dashboard.

Bonus: Is there a cypress.io badge for the main readme?

2022-02-01 08:24 UTC, bonndan approved these changes

2022-02-02 10:50 UTC, jenarp commented on development.md
> +In Nivio smoke tests are executed, for new commits to develop branch and master branch.
In Nivio, smoke tests are executed for new commits to the develop and master branch.

2022-02-02 10:51 UTC, jenarp approved these changes

2022-02-04 10:18 UTC, merged